# .streamlit/secrets.toml

OPENAI_API_KEY = "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"
